# .streamlit/secrets.toml

OPENAI_API_KEY = "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"
